# .streamlit/secrets.toml

OPENAI_API_KEY = "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"
